name: LightDreamAPI
version: ${project.version}
main: dev.lightdream.api.APIPlugin
authors: [ L1ghtDream ]
website: https://lightdream.dev
depend:
  - Vault
softdepend:
  - PlaceholderAPI
  - WorldEdit
  - WorldGuard
commands:
  ld-api:
    description: NA